### ISSUE TITLE
Can you provide a step by step approach to adding this to Angular-Schema-Form

### ISSUE THREAD

**Issue by jrothman** [Anthropic/angular-schema-form-external-options#1]
Hi Anthropic - Sounds like a really useful add-on however I just cannot get your add-on to work with A-S-F and it's likely lack of add-on experience on my part. Can you provide a working example with source code or a step by step guide to using it? Thanks!

**Comment by Anthropic** [comment]
Absolutely I'll get on it as soon as I get over my cold.

**Comment by jrothman** [comment]
Thanks! - and get well soon :-)

**Comment by Anthropic** [comment]
Bah! @jrothman I was missing some code I am going to have to add properly over the next week, I'm actually on holiday in Japan and tried in vein to rush this out before I left. The code is below which adds the directive, but I haven't fully tested it, I've started making an example and will try to finish it ASAP.

``` javascript
//Add to the bootstrap directive
schemaFormDecoratorsProvider.addMapping(
  'bootstrapDecorator',
  'select-external',
  'directives/decorators/bootstrap/external-options/external-options.html'
);
schemaFormDecoratorsProvider.createDirective(
  'select-external',
  'directives/decorators/bootstrap/external-options/external-options.html'
);
```

**Comment by jrothman** [comment]
Thanks - enjoy the holiday and then we can discuss further when you're back.

**Comment by Anthropic** [comment]
I'm back and I have started working on a fix, I am also working on an example page. I started this as part of a large project and unfortunately it turns out that it was more complex to separate than I had time to do minutes before catching a flight to leave for a month, apologies for that!

I plan to devote a portion of my weekend to sorting it out.

**Comment by jrothman** [comment]
Thanks – appreciate it!

Regards,
Joel

**Comment by Anthropic** [comment]
I finally have it working at home, with an example folder, but there is something small missing that makes the drop downs do that annoying thing in angular with the extra empty options which doesn't happen in the integrated instance at work, I will try to sort that this week and then push the update.

**Comment by jrothman** [comment]
Thanks Marcel – sounds like you’re almost there!

Regards,
Joel

**Comment by Anthropic** [comment]
Not sure if you noticed but I added an example folder a few months back, sorry for not updating the ticket, slipped my mind at the time.
