### ISSUE TITLE
Promise based source

### ISSUE THREAD

**Issue by jdpnielsen** [Anthropic/angular-schema-form-external-options#3]
I have created a [fork](https://github.com/jdpnielsen/angular-schema-form-external-options/tree/feat/promise-source) of this project, where I have added the ability to use a promise + formatter function by adding the following case:

``` javascript
else if (scope.form.promise && scope.form.formatter) {
    scope.form.promise.then(function(data) {
        var formmatedData = {
            titleMap: data.map(scope.form.formatter)
        };

        processOptions('data:' + scope.form.optionData, formmatedData, scope.form.selectedOption);
    });
} 
```

Usage example:

``` javascript

var form = [{
  key: 'city',
  type: 'select-external',
  promise: cityResource.getAll().$promise,
  formatter: function(each) {
    return { name: each.name, value: each.id };
  },
}];

var schema = {
  type: 'object',
  properties: {
    city: { type: 'string' }
  }
};
```

Assuming that cityResource is an angular-resource, with a getAll method returning an array of cities in `[{"name": "London", "id": "35431"}]` format.

Is this out of scope for this plugin? or would you be interested in integrating a more polished version of this feature?

**Comment by Anthropic** [comment]
@jdpnielsen wow April and I only just noticed this now!
I handle the same thing via the optionData attribute, it watches for changes so I handle my promise and then just update that object with the result and it updates the drop down. That way you can avoid having a function call in the form definition. I like what you have done, it looks like an easy way to do it for most users, but I'm actively trying to remove functions in the form definition in future, so sorry to say but for me it isn't something I want to add. I am sure it will be useful for other people though, so by all means rename the fork and add it as a separate add-on option :)
