### ISSUE TITLE
Emptying an array is ignored by the directive

### ISSUE THREAD

**Issue by ghost** [Anthropic/angular-schema-form-external-options#5]
Hi ! 

I had one issue with your add-on as I wanted to empty the optionData array in reaction of another input changes : 

> {
    "key"       : "postal_code",
     "onChange"  : "updateCities()"
},
{
    "key"       : "city",
    "type"      : "select-external",
    "optionData": "cities"
}

When the postal_code was wrong, I was emptying the cities array. But, the changes were not applied in the form. 

What I did to resolve this issue was to change the test you made on the newOptions array here (line 87) : 
`if (angular.isArray(newOptions) && newOptions.length)`
To
`if (angular.isArray(newOptions) && newOptions.length !== undefined )`

Could you tell me if this 'issue' is something wanted or if it is due to a configuration issue? 
Plus, as you one of the owner of angular-schema-form, will you integrate this add-on inside angular-schema-form, as I think this 'external' thing is something really usefull and kind of mandatory?

Thanks in advance for your answer!

**Comment by Anthropic** [comment]
Probably `if (angular.isArray(newOptions))` would be enough, length was being tested to avoid clearing the view by mistake as in my case at work I never wanted it cleared. So it is probably fine for it to be changed.

The origin of this add-on was actually the Material Design decorated I started where it is indeed part of the decorator. At that time I was not maintaining bootstrap or the main library, it was actually my work on the Material decorator that landed me the maintainer role.

It is absolutely something I intend to add into the library and I have done some work toward that, but not enough. Being the only maintainer it takes a while to find time to do such things :)

**Comment by ghost** [comment]
Thanks for your response !

Yes, actually in my code I removed the lenght test. I let it here for the example :)
Ok I understand. Sure it seems difficult to own and maintain a project like that... As I'm using this project now in my own, I will try to report the bug and give a solution if I find something like that in the future. 

Good luck :)

**Comment by Anthropic** [comment]
Closed thanks to PR #7
